// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2843db96-7d25-4cf5-8e67-71baed52dfb7',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'BDHadoopHumboldtCRP1_695484',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'eastus';
  process.env['SSHCERT'] = 'C:\HDInsight\azure-xplat-cli\test\myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplattesthdinsightRG/providers/Microsoft.HDInsight/clusters/xplattesthdinsightWindows?api-version=2015-03-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplattesthdinsightRG/providers/Microsoft.HDInsight/clusters/xplattesthdinsightWindows\",\"name\":\"xplattesthdinsightWindows\",\"type\":\"Microsoft.HDInsight/clusters\",\"location\":\"East US\",\"etag\":\"be47e32f-aa72-4f92-a401-3673f844cffc\",\"tags\":null,\"properties\":{\"clusterVersion\":\"3.2.7.743\",\"osType\":\"Windows\",\"clusterDefinition\":{\"kind\":\"Hadoop\"},\"computeProfile\":{\"roles\":[{\"name\":\"HeadNode\",\"targetInstanceCount\":2,\"hardwareProfile\":{\"vmSize\":\"Standard_D3\"},\"osProfile\":{\"windowsOperatingSystemProfile\":{\"rdpSettings\":{\"username\":\"xplattestrdpuser\",\"expiryDate\":\"2025-12-12T00:00:00\"}},\"linuxOperatingSystemProfile\":null}},{\"name\":\"workernode\",\"targetInstanceCount\":3,\"hardwareProfile\":{\"vmSize\":\"Standard_D3\"},\"osProfile\":{\"windowsOperatingSystemProfile\":{\"rdpSettings\":{\"username\":\"xplattestrdpuser\",\"expiryDate\":\"2025-12-12T00:00:00\"}},\"linuxOperatingSystemProfile\":null}}]},\"provisioningState\":\"Failed\",\"clusterState\":\"Error\",\"createdDate\":\"2015-11-23T21:38:28.657\",\"quotaInfo\":{\"coresUsed\":20},\"errors\":[{\"code\":\"PreClusterCreationValidationFailure\",\"message\":\"Pre cluster creation validation failed for cluster xplattesthdinsightWindows due to user error. \\r\\n                        Validation Report: Hosted service is already taken. Cannot continue to create cluster. Exception: \"}],\"connectivityEndpoints\":[{\"name\":\"HTTPS\",\"protocol\":\"TCP\",\"location\":\"xplattesthdinsightWindows.cloudapp.net\",\"port\":443},{\"name\":\"RDP\",\"protocol\":\"TCP\",\"location\":\"xplattesthdinsightWindows.cloudapp.net\",\"port\":3389}]}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1580',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '22db25d1-ef9b-45a8-abcc-71a684f88127',
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14978',
  'x-ms-correlation-request-id': '7a753c52-b015-478a-9050-7ef09447cab2',
  'x-ms-routing-request-id': 'WESTUS:20151123T215252Z:7a753c52-b015-478a-9050-7ef09447cab2',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Mon, 23 Nov 2015 21:52:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplattesthdinsightRG/providers/Microsoft.HDInsight/clusters/xplattesthdinsightWindows?api-version=2015-03-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplattesthdinsightRG/providers/Microsoft.HDInsight/clusters/xplattesthdinsightWindows\",\"name\":\"xplattesthdinsightWindows\",\"type\":\"Microsoft.HDInsight/clusters\",\"location\":\"East US\",\"etag\":\"be47e32f-aa72-4f92-a401-3673f844cffc\",\"tags\":null,\"properties\":{\"clusterVersion\":\"3.2.7.743\",\"osType\":\"Windows\",\"clusterDefinition\":{\"kind\":\"Hadoop\"},\"computeProfile\":{\"roles\":[{\"name\":\"HeadNode\",\"targetInstanceCount\":2,\"hardwareProfile\":{\"vmSize\":\"Standard_D3\"},\"osProfile\":{\"windowsOperatingSystemProfile\":{\"rdpSettings\":{\"username\":\"xplattestrdpuser\",\"expiryDate\":\"2025-12-12T00:00:00\"}},\"linuxOperatingSystemProfile\":null}},{\"name\":\"workernode\",\"targetInstanceCount\":3,\"hardwareProfile\":{\"vmSize\":\"Standard_D3\"},\"osProfile\":{\"windowsOperatingSystemProfile\":{\"rdpSettings\":{\"username\":\"xplattestrdpuser\",\"expiryDate\":\"2025-12-12T00:00:00\"}},\"linuxOperatingSystemProfile\":null}}]},\"provisioningState\":\"Failed\",\"clusterState\":\"Error\",\"createdDate\":\"2015-11-23T21:38:28.657\",\"quotaInfo\":{\"coresUsed\":20},\"errors\":[{\"code\":\"PreClusterCreationValidationFailure\",\"message\":\"Pre cluster creation validation failed for cluster xplattesthdinsightWindows due to user error. \\r\\n                        Validation Report: Hosted service is already taken. Cannot continue to create cluster. Exception: \"}],\"connectivityEndpoints\":[{\"name\":\"HTTPS\",\"protocol\":\"TCP\",\"location\":\"xplattesthdinsightWindows.cloudapp.net\",\"port\":443},{\"name\":\"RDP\",\"protocol\":\"TCP\",\"location\":\"xplattesthdinsightWindows.cloudapp.net\",\"port\":3389}]}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1580',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '22db25d1-ef9b-45a8-abcc-71a684f88127',
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-reads': '14978',
  'x-ms-correlation-request-id': '7a753c52-b015-478a-9050-7ef09447cab2',
  'x-ms-routing-request-id': 'WESTUS:20151123T215252Z:7a753c52-b015-478a-9050-7ef09447cab2',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Mon, 23 Nov 2015 21:52:52 GMT',
  connection: 'close' });
 return result; }]];