// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2843db96-7d25-4cf5-8e67-71baed52dfb7',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'BDHadoopHumboldtCRP1_695484',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'eastus';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplatTestRgHDInsightClusterCreate8442/providers/Microsoft.HDInsight/clusters/xplatTestHDInsightClusterCreate165?api-version=2015-03-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTestRgHDInsightClusterCreate8442' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'x-ms-correlation-request-id': 'f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'x-ms-routing-request-id': 'WESTUS:20151127T225216Z:f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 27 Nov 2015 22:52:15 GMT',
  connection: 'close',
  'content-length': '129' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplatTestRgHDInsightClusterCreate8442/providers/Microsoft.HDInsight/clusters/xplatTestHDInsightClusterCreate165?api-version=2015-03-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTestRgHDInsightClusterCreate8442' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'x-ms-correlation-request-id': 'f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'x-ms-routing-request-id': 'WESTUS:20151127T225216Z:f8ffd53c-2662-45e9-a9be-2ab082d4f093',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 27 Nov 2015 22:52:15 GMT',
  connection: 'close',
  'content-length': '129' });
 return result; }]];