// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2843db96-7d25-4cf5-8e67-71baed52dfb7',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'BDHadoopHumboldtCRP1_695484',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    registeredProviders: [],
    _eventsCount: '1',
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_ARM_TEST_LOCATION'] = 'eastus';
  process.env['SSHCERT'] = 'C:\HDInsight\azure-xplat-cli\test\myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplatTestRgHDInsightClusterCreate5959/providers/Microsoft.HDInsight/clusters/xplatTestHDInsightClusterCreate3188/changerdpsetting?api-version=2015-03-01-preview', '*')
  .reply(409, "{\"code\":\"Conflict\",\"message\":\"User cannot be enabled because there is already an existing user of the same type. UserType: 'Rdp'\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '130',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'x-ms-correlation-request-id': 'e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'x-ms-routing-request-id': 'WESTUS:20151124T072122Z:e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 24 Nov 2015 07:21:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/2843db96-7d25-4cf5-8e67-71baed52dfb7/resourceGroups/xplatTestRgHDInsightClusterCreate5959/providers/Microsoft.HDInsight/clusters/xplatTestHDInsightClusterCreate3188/changerdpsetting?api-version=2015-03-01-preview', '*')
  .reply(409, "{\"code\":\"Conflict\",\"message\":\"User cannot be enabled because there is already an existing user of the same type. UserType: 'Rdp'\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '130',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-powered-by': 'ASP.NET',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'x-ms-correlation-request-id': 'e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'x-ms-routing-request-id': 'WESTUS:20151124T072122Z:e5c1fb43-1cf7-4762-a788-0500a73bddc6',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 24 Nov 2015 07:21:22 GMT',
  connection: 'close' });
 return result; }]];